### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by p0mbe** [Escape-Technologies/graphenum#35]
When run, the file spits out an ImportError.

![graphenum](https://user-images.githubusercontent.com/112125958/193752006-9fed89c0-936c-49a2-aee1-38ca17d2256f.png)

This occurs after installing via pip and cloning the repo. I am using Python3.8

**Comment by c3b5aw** [comment]
Hello @p0mbe,

Thanks you for catching this issue.
I just released v0.0.3 which will fix this.

Good luck for your CTF :)
